apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth
  namespace: oauth
spec:
  rules:
    - host: oauth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oauth-service
                port:
                  number: 80
