apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
  namespace: oauth
type: Opaque
stringData:
  CLIENT_ID: "PUT_CLIENT_ID_HERE"
  CLIENT_SECRET: "PUT_CLIENT_SECRET_HERE"
  JWT_SECRET: "PUT_JWT_SECRET_HERE"
