apiVersion: v1
kind: Secret
metadata:
  name: oauth-fastapi-secret
  namespace: oauth-fastapi
type: Opaque
stringData:
  OAUTH_CLIENT_ID: "replace-me"
  OAUTH_CLIENT_SECRET: "replace-me"
  JWT_SECRET: "replace-me"
